# This workflow builds the project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code base
        # https://github.com/actions/checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        # https://github.com/actions/setup-java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          check-latest: true

      - name: Prepare Maven cache
        # https://github.com/actions/cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Verify artifacts
        run: mvn -B -Pintegration-tests verify

      - name: Prepare Sonar cache
        # https://github.com/actions/cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sonar/cache
          key: sonar

      - name: Upload coverage report to Sonar
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

      - name: Prepare main documentation
        id: prepare-main-documentation
        if: github.ref == 'refs/heads/main'
        run: |
          TAG_NAME="current"
          echo "::set-output name=dest_dir::${TAG_NAME}"

      - name: Publish main documentation
        # https://github.com/peaceiris/actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.ref == 'refs/heads/main'
        with:
          cname: sync-packagejson-version-maven-plugin.ingogriebsch.de
          commit_message: 'docs: publish main documentation to gh-pages'
          destination_dir: ${{ steps.prepare-main-documentation.outputs.dest_dir }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_branch: gh-pages
          publish_dir: ./target/generated-docs
          user_email: 'github-actions[bot]@users.noreply.github.com'
          user_name: 'github-actions[bot]'
